# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[(1, 'low priority'), (2, 'medium-rare priority'), (3, 'medium priority'), (4, 'medium-well priority'), (5, 'top priority')], max_length=20),
        ),
    ]
