# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20170331_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[(1, 'low priority'), (2, 'medium-rare priority'), (3, 'medium priority'), (4, 'medium-well priority'), (5, 'top priority')], default='(1, low priority)', max_length=20),
        ),
    ]
