# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20170331_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[(1, 'low priority'), (2, 'medium-rare priority'), (3, 'medium priority'), (4, 'medium-well priority'), (5, 'top priority')], default=1, max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[(1, 'not started'), (2, 'in progress'), (3, 'completed')], default=1, max_length=20),
        ),
    ]
