# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 04:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0004_auto_20170401_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('1', 'low priority'), ('2', 'medium-rare priority'), ('3', 'medium priority'), ('4', 'medium-well priority'), ('5', 'top priority')], default='1', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('1', 'not started'), ('2', 'in progress'), ('3', 'completed')], default='1', max_length=20),
        ),
    ]
